import type { Strategy } from '@/types/domain'

export const STRATEGIES: Strategy[] = [
  {
    id: 'brandable',
    name: 'Brandable 1-Word .com',
    description: 'Premium one-word .com domains with high brandability',
    targetTLD: '.com',
    minLength: 3,
    maxLength: 10,
    filters: { hasTraffic: false, aged: true, brandScore: 90 },
    budgetPerDomain: 50000,
    expectedProfit: 200000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'crypto',
    name: 'Crypto/NFT .com',
    description: 'Token name .com domains before major launches',
    keywords: ['bonk', 'wif', 'pepe', 'maga', 'shib', 'doge', 'sol', 'eth', 'btc'],
    targetTLD: '.com',
    budgetPerDomain: 25000,
    expectedProfit: 500000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'ai',
    name: 'AI .com/.ai',
    description: 'AI-related domains with explosive growth potential',
    keywords: ['gpt', 'agent', 'neural', 'quantum', 'claude', 'llm', 'ml', 'ai'],
    targetTLDs: ['.com', '.ai'],
    budgetPerDomain: 30000,
    expectedProfit: 300000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'lll',
    name: '3-Letter .com',
    description: 'Premium LLL.com domains - finite supply, Chinese buyer premium',
    pattern: /^[a-z]{3}\.com$/,
    budgetPerDomain: 100000,
    expectedProfit: 500000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'geo-service',
    name: 'Geo + Service .com',
    description: 'Location-based service domains (e.g., miamipainter.com)',
    pattern: /^(miami|dubai|london|newyork|tokyo|paris|singapore|sydney)[a-z]+\.com$/,
    budgetPerDomain: 15000,
    expectedProfit: 75000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'traffic',
    name: 'Expired with Traffic',
    description: 'Expired domains with existing organic traffic',
    minTraffic: 1000,
    budgetPerDomain: 10000,
    expectedProfit: 50000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'pumpfun',
    name: 'Pump.fun Names',
    description: 'Snipe token domains before Raydium listing',
    keywords: ['pump', 'moon', 'degen', 'ape', 'chad'],
    targetTLDs: ['.com', '.sol', '.io'],
    budgetPerDomain: 5000,
    expectedProfit: 100000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'typo',
    name: 'Typo Domains',
    description: 'Strategic typos of major brands (park with ads)',
    keywords: ['facebook', 'youtube', 'instagram', 'twitter', 'amazon'],
    budgetPerDomain: 20000,
    expectedProfit: 150000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'one-word-io',
    name: 'One-Word .io/.ai',
    description: 'Premium tech domains (nexus.ai, forge.io)',
    targetTLDs: ['.io', '.ai'],
    minLength: 3,
    maxLength: 8,
    budgetPerDomain: 20000,
    expectedProfit: 120000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
  {
    id: 'numbers',
    name: 'Number Domains',
    description: 'Lucky number domains (888.io, 777.com) - Chinese premium',
    pattern: /^[0-9]{3,4}\.(io|com|ai)$/,
    budgetPerDomain: 30000,
    expectedProfit: 200000,
    domainsBought: 0,
    totalInvested: 0,
    totalProfit: 0,
    roi: 0,
    liveAuctions: 0,
    enabled: true,
  },
]
